const countryList = {
    
    BGN: "BG",
    BRL: "BR",
    BSD: "BS",
    NOK: "BV",
    CAD: "CA",
    XAF: "CF",
    CHF: "CH",
    CNY: "CN",
    CZK: "CZ",
    DKK: "DK",
    EUR: "FR",
    GBP: "GB",
    HKD: "HK",
    HUF: "HU",
    IDR: "ID",
    INR: "IN",
    ISK: "IS",
    JPY: "JP",
    KRW: "KR",
    MXN: "MX",
    MYR: "MY",
    XPF: "NC",
    NZD: "NZ",
    PHP: "PH",
    PLN: "PL",
    RON: "RO",
    SEK: "SE",
    SGD: "SG",
    THB: "TH",
    TRY: "TR",
    USD: "US",
    ZAR: "ZA",
  };